USE master; IF DB_ID('OrderNMC_IntTest') IS NOT NULL BEGIN ALTER DATABASE OrderNMC_IntTest SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE OrderNMC_IntTest; END; PRINT 'test database dropped';
