"""Production configuration model and generators (wizard STEP 6).

A single ``HoConfig`` captures everything chosen in the wizard. From it we
generate:

* ``config\\ho.env``     - read by backend/config/database.py and api/app.py
                           (and loaded by the Windows-service host at startup).
* ``config\\settings.json`` - full resolved configuration, for support/audit.
* ``frontend\\config.js``   - injects window.__UNINEX_API_BASE__ for the SPA.

No schema is created here; the database is provisioned by restoring the bundled
NEXORA_PLATFORM.bak (see sql_deployer).
"""
import json
import socket
from dataclasses import dataclass, field
from pathlib import Path

from . import (
    CONFIG_DIR_NAME,
    DEFAULT_DATABASE,
    DEFAULT_HOST,
    DEFAULT_PORT,
    DEFAULT_INSTALL_PATH,
    ENV_FILE_NAME,
    SETTINGS_FILE_NAME,
)

DEFAULT_DRIVER = "ODBC Driver 17 for SQL Server"


def default_public_host():
    """Hostname a remote browser can use to reach this HO server."""
    try:
        return socket.gethostname()
    except Exception:
        return "localhost"


@dataclass
class HoConfig:
    # SQL Server (STEP 4)
    sql_server: str = "localhost"
    auth_mode: str = "SQL"            # "SQL" | "WINDOWS"
    sql_username: str = "sa"
    sql_password: str = ""
    database: str = DEFAULT_DATABASE
    sql_driver: str = DEFAULT_DRIVER

    # Application (STEP 3 / 6)
    install_path: str = DEFAULT_INSTALL_PATH
    public_host: str = field(default_factory=default_public_host)
    host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT

    # ---- derived paths ----------------------------------------------------

    @property
    def root(self) -> Path:
        return Path(self.install_path)

    @property
    def config_dir(self) -> Path:
        return self.root / CONFIG_DIR_NAME

    @property
    def env_path(self) -> Path:
        return self.config_dir / ENV_FILE_NAME

    @property
    def settings_path(self) -> Path:
        return self.config_dir / SETTINGS_FILE_NAME

    @property
    def log_path(self) -> Path:
        return self.root / "logs"

    @property
    def upload_path(self) -> Path:
        return self.root / "uploads"

    @property
    def frontend_dir(self) -> Path:
        return self.root / "frontend"

    @property
    def api_url(self) -> str:
        return f"http://{self.public_host}:{self.port}"

    @property
    def frontend_url(self) -> str:
        # The backend service serves the SPA on the same origin.
        return f"http://{self.public_host}:{self.port}"

    # ---- generators -------------------------------------------------------

    def env_content(self) -> str:
        lines = [
            "# Generated by HO_Setup. Do not edit by hand; re-run the installer.",
            f"DB_SERVER={self.sql_server}",
            f"DB_DATABASE={self.database}",
            f"DB_DRIVER={self.sql_driver}",
            f"DB_AUTH_MODE={self.auth_mode.upper()}",
        ]
        if self.auth_mode.upper() != "WINDOWS":
            lines.append(f"DB_USERNAME={self.sql_username}")
            lines.append(f"DB_PASSWORD={self.sql_password}")
        lines += [
            f"UNINEX_API_URL={self.api_url}",
            f"UNINEX_FRONTEND_URL={self.frontend_url}",
            f"UNINEX_FRONTEND_DIR={self.frontend_dir}",
            f"UNINEX_CORS_ORIGINS={self.api_url}",
            f"UNINEX_HOST={self.host}",
            f"UNINEX_PORT={self.port}",
            f"UNINEX_LOG_PATH={self.log_path}",
            f"UNINEX_UPLOAD_PATH={self.upload_path}",
        ]
        return "\n".join(lines) + "\n"

    def settings_dict(self) -> dict:
        return {
            "database": {
                "server": self.sql_server,
                "database": self.database,
                "driver": self.sql_driver,
                "auth_mode": self.auth_mode.upper(),
                "username": self.sql_username
                if self.auth_mode.upper() != "WINDOWS" else None,
            },
            "application": {
                "install_path": str(self.root),
                "public_host": self.public_host,
                "host": self.host,
                "port": self.port,
                "api_url": self.api_url,
                "frontend_url": self.frontend_url,
                "frontend_dir": str(self.frontend_dir),
                "log_path": str(self.log_path),
                "upload_path": str(self.upload_path),
            },
        }

    def config_js(self) -> str:
        return f'window.__UNINEX_API_BASE__ = "{self.api_url}";\n'

    def write_config_files(self, log=None):
        """Write ho.env + settings.json. Returns the two paths."""
        log = log or (lambda msg: None)
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.env_path.write_text(self.env_content(), encoding="utf-8")
        log(f"wrote {self.env_path}")
        self.settings_path.write_text(
            json.dumps(self.settings_dict(), indent=2), encoding="utf-8"
        )
        log(f"wrote {self.settings_path}")
        return self.env_path, self.settings_path
