export const colors = {
  accent: '#2563eb',
  accentStrong: '#1d4ed8',
  accentSoft: '#dbeafe',
  success: '#059669',
  warning: '#d97706',
  danger: '#dc2626',
  info: '#0891b2',
  slate900: '#0f172a',
  slate700: '#334155',
  slate500: '#64748b',
  slate300: '#cbd5e1',
  slate200: '#e2e8f0',
  slate100: '#f1f5f9',
  white: '#ffffff',
} as const

export const semanticColors = {
  surface: 'var(--ds-surface)',
  surfaceMuted: 'var(--ds-surface-muted)',
  surfaceSubtle: 'var(--ds-surface-subtle)',
  border: 'var(--ds-border)',
  borderStrong: 'var(--ds-border-strong)',
  textPrimary: 'var(--ds-text-primary)',
  textSecondary: 'var(--ds-text-secondary)',
  textMuted: 'var(--ds-text-muted)',
  accent: 'var(--ds-accent)',
  success: 'var(--ds-success)',
  warning: 'var(--ds-warning)',
  danger: 'var(--ds-danger)',
  info: 'var(--ds-info)',
} as const
