"""Renders the project dashboard (PROJECT_STATUS.md)."""

from __future__ import annotations

from ..core.models import ModuleStatus, VersionInfo
from .markdown import MarkdownBuilder


class DashboardBuilder:
    def render(
        self,
        version: VersionInfo,
        modules: list[ModuleStatus],
        recent_work: list[str],
        generated_on: str,
    ) -> str:
        overall = self._overall(modules)
        md = MarkdownBuilder()
        md.heading("NEXORA Platform — Project Status", 1)
        md.paragraph(
            "Auto-generated by the NEXORA Development Framework "
            f"(`dashboard build`). Last updated: {generated_on}."
        )

        md.heading("Summary", 2)
        md.table(
            ["Metric", "Value"],
            [
                ["Current Version", f"{version.semver} (build {version.build_number})"],
                ["Release Name", version.release_name or "—"],
                ["Overall Completion", f"{overall}%"],
                ["Modules Tracked", str(len(modules))],
            ],
        )

        md.heading("Module Completion", 2)
        if modules:
            md.table(
                ["Module", "Status", "Completion", "Owner", "Milestone"],
                [
                    [
                        m.name,
                        m.status,
                        self._bar(m.completion_pct),
                        m.owner or "—",
                        m.milestone or "—",
                    ]
                    for m in modules
                ],
            )
        else:
            md.paragraph("_No modules configured._")

        md.heading("Pending Work", 2)
        pending = [m for m in modules if m.completion_pct < 100]
        if pending:
            for m in pending:
                md.bullet(f"{m.name} — {100 - m.completion_pct}% remaining ({m.status})")
            md.blank()
        else:
            md.paragraph("_All tracked modules complete._")

        md.heading("Recent Work", 2)
        if recent_work:
            for item in recent_work:
                md.bullet(item)
            md.blank()
        else:
            md.paragraph("_No recent commits found._")

        return md.render()

    @staticmethod
    def _overall(modules: list[ModuleStatus]) -> int:
        if not modules:
            return 0
        return round(sum(m.completion_pct for m in modules) / len(modules))

    @staticmethod
    def _bar(pct: int) -> str:
        filled = max(0, min(10, round(pct / 10)))
        return f"{'█' * filled}{'░' * (10 - filled)} {pct}%"
