"""Renders the documentation index (docs/INDEX.md)."""

from __future__ import annotations

from ..core.models import AdrRecord, BusinessRule, DocRecord
from .markdown import MarkdownBuilder


class IndexBuilder:
    def render(
        self,
        docs: list[DocRecord],
        adrs: list[AdrRecord],
        rules: list[BusinessRule],
        generated_on: str,
    ) -> str:
        md = MarkdownBuilder()
        md.heading("NEXORA Platform — Documentation Index", 1)
        md.paragraph(
            "Auto-generated by the NEXORA Development Framework "
            f"(`docs build`). Last updated: {generated_on}."
        )

        md.heading("Documents", 2)
        if docs:
            md.table(
                ["Module", "Document", "Version", "Status", "Owner", "Updated", "Path"],
                [
                    [
                        d.module,
                        f"[{d.document}]({d.path})",
                        d.version or "—",
                        d.status or "—",
                        d.owner or "—",
                        d.updated_date or "—",
                        d.path,
                    ]
                    for d in docs
                ],
            )
        else:
            md.paragraph("_No documents indexed._")

        md.heading("Architecture Decision Records", 2)
        if adrs:
            md.table(
                ["ADR", "Title", "Status", "Date", "Path"],
                [
                    [a.identifier, f"[{a.title}]({a.path})", a.status, a.date or "—", a.path]
                    for a in adrs
                ],
            )
        else:
            md.paragraph("_No ADRs recorded._")

        md.heading("Business Rules", 2)
        if rules:
            md.table(
                ["ID", "Name", "Module", "Version", "Priority", "Status"],
                [
                    [r.identifier, r.name, r.module, r.version, r.priority, r.status]
                    for r in rules
                ],
            )
        else:
            md.paragraph("_No business rules registered._")

        return md.render()
